---
- name:             Create/Update MySQL {{ mysql_user }} user
  mysql_user:       name={{ mysql_user }}
                    password="{{ lookup('password', '~/jcid/repositories/webserver/ansible/files/credentials/' + inventory_hostname + '/mysql/' + mysql_user + ' length=30 chars=ascii_letters') }}"
                    host={{ item }}
                    priv={{ mysql_priv | default('') }}
                    state=present
  with_items:       "{{ mysql_hosts | default(['localhost']) }}"
